### ISSUE TITLE
项目部署的问题，数据库建表语句和字段未知

### ISSUE THREAD

**Issue by YY-oops** [rule-engine/rule-engine-front#13]
您好，
     您的项目写的非常好，注释非常完善，代码结构非常清晰。
     但是，我在按照您的doc进行后端部署时发现需要数据库建库建表，但是您在仓库中没有给出数据库表和字段，以及建表语句。
     希望您能补充。感谢您

**Comment by YY-oops** [comment]
非常抱歉，在resources目录下的sql文件夹中发现了rule-engine.sql文件，是我的疏忽。
感谢您的开源奉献精神

**Comment by dingqianwen** [comment]
你好，这个在resource文件夹下有个sql文件，执行下就好了。

发自我的iPhone

**Comment by dingqianwen** [comment]
好的，后面有问题可以联系我。

发自我的iPhone
