### ISSUE TITLE
前端部署，踩坑排雷

### ISSUE THREAD

**Issue by YY-oops** [rule-engine/rule-engine-front#14]
我是个小白，我按照详细文档中的部署方式进行前端部署时，按照描述
    “// 请求后端服务器接口前缀
    const requestBaseURL = "你的后端地址:端口号";”
我这样配置：const requestBaseURL = "192.168.43.114:8010";弄了一上午都没弄成功
后来才发现这应该是个URL地址，所以我改成了：const requestBaseURL = "http://192.168.43.114:8010/";然后就成功了
算是给像我一样的小白一个经验吧。

**Comment by dingqianwen** [comment]
> 我是个小白，我按照详细文档中的部署方式进行前端部署时，按照描述
> “ //请求服务器接口插入
> 常量requestBaseURL =“你的重定向地址：端口号”;“
> 我这样的配置：const requestBaseURL =“ 192.168.43.114:8010”;弄成一个上午都没弄成功
> 后来才发现这应该是个URL地址，所以我改变成：const requestBaseURL =“ http://192.168.43.114:8010/ ”; 然后就成功了
> 算是给像我一样的小白一个经验吧。

非常抱歉给你带来困扰与不便，同时也多谢你的反馈，后期我们会陆续优化文档。
