### ISSUE TITLE
bug: 首页底部留白过多

### ISSUE THREAD

**Issue by stephenLYZ** [rule-engine/rule-engine-front#16]
![image](https://user-images.githubusercontent.com/11830681/111604611-76dd4900-8810-11eb-977a-2fc1c4df1d8f.png)

视觉上看起来有点奇怪，可以优化。

**Comment by dingqianwen** [comment]
你好，非常感谢你提出宝贵意见，如果可以的话欢迎提交更加优质的代码以及设计，或者添加我联系方式倾听你更多的意见以及解决方案！
